config/routes.rb
Rails.application.routes.draw do
  resources :offers, only: :index
   root 'offers#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  respond_to :html
  before_action :init_fyber_client

  def index
    @offers = @client.offers
    @message = @client.message

    respond_with @offers
  end

  private

  def init_fyber_client
    @client = FyberClient.new(search_params).get
  end

  def search_params
    params.permit(:uid, :pub0, :page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FyberOffers
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    .jumbotron.text-center
      .container
        %h1 Fyber Challenge

    .container
      .row
        = yield

app/views/offers/index.html.haml
.panel.panel-default
  .panel-heading
    = @message
  .panel-body
    = form_tag offers_path, method: :get, class: "form-inline" do
      .form-group
        = text_field_tag :uid, params[:uid], class: 'form-control', placeholder: "uid"
      .form-group
        = text_field_tag :pub0, params[:pub0], class: 'form-control', placeholder: "pub0"
      .form-group
        = text_field_tag :page, params[:page], class: 'form-control', type: :number, placeholder: "page"
      = submit_tag 'Show offers', class: 'btn btn-primary'
  %ul.list-group
    - @offers.each do |offer|
      %li.list-group-item
        .offer
          .title= offer[:title]
          .payout= offer[:payout]
          .thumbnail= image_tag offer[:thumbnail][:lowres]

    - if @offers.empty?
      %li.list-group-item
        .no_offers No offers